### ISSUE TITLE
Animated: `useNativeDriver` Warning.

### ISSUE THREAD

**Issue by sareh88** [RafaelAugustoS/react-native-popup-ui#13]
**Issue Description**

node: v10.15.3
yarn: 1.12.3
react-native: 0.62.0
popup-ui: 1.0.10

_Expected behaviour:_
no warning...

_Actual behaviour_
Get some warning in react-native console :  
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by joelhenrique2000** [comment]
The temporary fix is here: https://github.com/RafaelAugustoS/react-native-popup-ui/pull/15/commits/314cc090ee9c8ccd4146e35bb3ba21e9244eee09
