### ISSUE TITLE
undefined is not an object (evaluating '_popupUi.PopupAlert.show')

### ISSUE THREAD

**Issue by justinhoo888** [RafaelAugustoS/react-native-popup-ui#21]
Hi all,

I hit this error, how to solve this ya?

Please help. Thank you.

**Comment by EnnnnoN** [comment]
You need to import "Root" from popup-ui. Follow the tutorial exact!

**Comment by RafaelAugustoS** [comment]
Yes, how @EnnnnoN said, you need import root to works, open **App.js** in examples.
