### ISSUE TITLE
BackgroundColor Error on Android device

### ISSUE THREAD

**Issue by FloDev974** [RafaelAugustoS/react-native-popup-ui#5]
Hello I have BackgroundColor Error when I add `<Root>...</Root>` or expo app crashed without error just on Android device on IOS is work.

Example: https://snack.expo.io/@dionys/4c551f

I need help please.

**Comment by ronymmoura** [comment]
+1

**Comment by RafaelAugustoS** [comment]
Ok. I going to check this.

**Comment by RafaelAugustoS** [comment]
> Hello I have BackgroundColor Error when I add `<Root>...</Root>` or expo app crashed without error just on Android device on IOS is work.
> 
> Example: https://snack.expo.io/@dionys/4c551f
> 
> I need help please.


Is the problem you are experiencing only on the expo (web), or on the actual device as well? I tried to simulate the problem here, and failed, started the project by expo, installed the dependency and used the same code you provided. But it worked.

**Comment by jontacky** [comment]
Hi, 
I had this same exact issue yesterday and after a few checks I realised some version of react-native does not allow 'backgroundColor' to be null.

I did this on the Toast.js:

<View style={[styles.timing, { backgroundColor: color || 'transparent'}]} />

my app crashes no more. You can take a look

**Comment by RafaelAugustoS** [comment]
> Hello I have BackgroundColor Error when I add `<Root>...</Root>` or expo app crashed without error just on Android device on IOS is work.
> 
> Example: https://snack.expo.io/@dionys/4c551f
> 
> I need help please.

the problem has been solved thanks to the help of @jontacky 

You can try here: https://snack.expo.io/@rafaelaugusto/popup-ui

**Comment by FloDev974** [comment]
It work thanks @jontacky  and @RafaelAugustoS
